//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_Custom_Exception.EntityObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentContactDetails
    {
        public int Id { get; set; }
        public string State { get; set; }
        public string Adreess { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Contact { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
