//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPI_Custom_Exception.EmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeModel", Namespace="http://schemas.datacontract.org/2004/07/Abhishek_POC_BusinessModel.BusinessObject" +
        "sModel")]
    [System.SerializableAttribute()]
    public partial class EmployeeModel : WEBAPI_Custom_Exception.EmployeeService.EventBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventBase", Namespace="http://schemas.datacontract.org/2004/07/Abhishek_POC_BusinessModel.Utility")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel))]
    public partial class EventBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployeeList", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeeListResponse")]
        WEBAPI_Custom_Exception.EmployeeService.EmployeeModel[] getEmployeeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployeeList", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeeListResponse")]
        System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel[]> getEmployeeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployee", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeeResponse")]
        WEBAPI_Custom_Exception.EmployeeService.EmployeeModel getEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getEmployee", ReplyAction="http://tempuri.org/IEmployeeService/getEmployeeResponse")]
        System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel> getEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        WEBAPI_Custom_Exception.EmployeeService.EmployeeModel AddEmployee(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel> AddEmployeeAsync(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/UpdateEmployeeResponse")]
        WEBAPI_Custom_Exception.EmployeeService.EmployeeModel UpdateEmployee(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel> UpdateEmployeeAsync(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/RemoveEmployee", ReplyAction="http://tempuri.org/IEmployeeService/RemoveEmployeeResponse")]
        bool RemoveEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/RemoveEmployee", ReplyAction="http://tempuri.org/IEmployeeService/RemoveEmployeeResponse")]
        System.Threading.Tasks.Task<bool> RemoveEmployeeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : WEBAPI_Custom_Exception.EmployeeService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<WEBAPI_Custom_Exception.EmployeeService.IEmployeeService>, WEBAPI_Custom_Exception.EmployeeService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WEBAPI_Custom_Exception.EmployeeService.EmployeeModel[] getEmployeeList() {
            return base.Channel.getEmployeeList();
        }
        
        public System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel[]> getEmployeeListAsync() {
            return base.Channel.getEmployeeListAsync();
        }
        
        public WEBAPI_Custom_Exception.EmployeeService.EmployeeModel getEmployee(int id) {
            return base.Channel.getEmployee(id);
        }
        
        public System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel> getEmployeeAsync(int id) {
            return base.Channel.getEmployeeAsync(id);
        }
        
        public WEBAPI_Custom_Exception.EmployeeService.EmployeeModel AddEmployee(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity) {
            return base.Channel.AddEmployee(blogEntity);
        }
        
        public System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel> AddEmployeeAsync(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity) {
            return base.Channel.AddEmployeeAsync(blogEntity);
        }
        
        public WEBAPI_Custom_Exception.EmployeeService.EmployeeModel UpdateEmployee(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity) {
            return base.Channel.UpdateEmployee(blogEntity);
        }
        
        public System.Threading.Tasks.Task<WEBAPI_Custom_Exception.EmployeeService.EmployeeModel> UpdateEmployeeAsync(WEBAPI_Custom_Exception.EmployeeService.EmployeeModel blogEntity) {
            return base.Channel.UpdateEmployeeAsync(blogEntity);
        }
        
        public bool RemoveEmployee(int id) {
            return base.Channel.RemoveEmployee(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveEmployeeAsync(int id) {
            return base.Channel.RemoveEmployeeAsync(id);
        }
    }
}
